services:
  postgres:
    image: postgres:latest
    container_name: resqlink-pg
    environment:
      POSTGRES_USER: gihyun
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resqlink
    ports:
      - "5432:5432"
    volumes:
      - resqlink-pg:/var/lib/postgresql/data

  redis-stack:
    image: redis/redis-stack:latest
    container_name: resqlink-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - resqlink-redis:/data

volumes:
  resqlink-pg:
  resqlink-redis:
