@hostname=localhost
@port=3002
@host={{hostname}}:{{port}}

### Get Disaster Reports

GET http://{{host}}/api/disaster-reports

### Get User's Disaster Reports

@userId=ea5d6daa-2ba6-454a-88bd-f712cd3d3c8b
GET http://{{host}}/api/users/{{userId}}/disaster-reports


