@hostname=localhost
@port=3002
@host={{hostname}}:{{port}}

### 

# @name Get Disaster Reports
GET http://{{host}}/api/disaster-reports

###

# @name Get User's Disaster Reports
@userId=ea5d6daa-2ba6-454a-88bd-f712cd3d3c8b
@reporterId=49d6af2f-b592-45a7-afee-2f9de0de2491
GET http://{{host}}/api/users/{{reporterId}}/disaster-reports

### 

# @name WebSocket (WS)
WS ws://{{host}}/ws

### 

# @name WS Save Location
WS ws://{{host}}/ws

{ "event": "disaster:save_location", "data": { "location": { "longitude": 30, "latitude": 18, "address": "Local McDonald's" }, "userId": "ea5d6daa-2ba6-454a-88bd-f712cd3d3c8b" } }

###
